# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='globaltool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('varname', models.CharField(max_length=50)),
                ('varid', models.CharField(max_length=50)),
                ('varpath', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-30 16:30:11'),
        ),
    ]
