# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memuid',
            old_name='memuname',
            new_name='submemuname',
        ),
        migrations.AddField(
            model_name='memulist',
            name='memunameid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='memulist',
            name='memuname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
