# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0002_auto_20190104_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('recordclass', models.CharField(max_length=150)),
                ('recordvalue', models.TextField(max_length=10000)),
                ('logtime', models.DateTimeField(default='2019-01-04 10:15:59')),
            ],
        ),
    ]
