# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0003_recordlogtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='memuid',
            name='submemuurl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-05 14:13:23'),
        ),
    ]
