# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0004_auto_20190105_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-05 14:13:39'),
        ),
    ]
