# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0005_auto_20190105_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='grayphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('expirytime', models.CharField(max_length=30, null=True)),
                ('phoneencrypt', models.CharField(max_length=150, null=True)),
                ('online', models.CharField(max_length=10)),
                ('createuser', models.CharField(max_length=30)),
                ('createtime', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedisHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redis_ip', models.GenericIPAddressField()),
                ('redis_port', models.CharField(max_length=20)),
                ('redis_pass', models.CharField(max_length=50, null=True)),
                ('project_owner', models.CharField(max_length=50, null=True)),
                ('project_principal', models.CharField(max_length=20, null=True)),
                ('typename', models.CharField(max_length=20, null=True)),
                ('typeid', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-07 17:59:34'),
        ),
    ]
