# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0006_auto_20190107_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='redishost',
            name='proxy_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-08 09:00:15'),
        ),
    ]
