# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0007_auto_20190108_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='redishost',
            name='admin_addr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='redishost',
            name='admin_port',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-08 17:14:33'),
        ),
    ]
