# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0010_auto_20190109_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansible_host',
            name='hostname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ansible_host',
            name='hostport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ansible_host',
            name='idc_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ansible_host',
            name='project_owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ansible_host',
            name='ansible_groupid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recordlogtable',
            name='logtime',
            field=models.DateTimeField(default='2019-01-11 15:07:36'),
        ),
    ]
